BEGIN:VCALENDAR
VERSION:2.0
METHOD:PUBLISH
BEGIN:VEVENT
DTSTART: $ICSStartDate
DTEND: $ICSEndDate
TRANSP:OPAQUE
SEQUENCE:0
UID:
DTSTAMP: $ICSTimeStamp
SUMMARY: $Event.Title
PRIORITY:1
CLASS:PUBLIC
BEGIN:VALARM
TRIGGER:-PT1440M
ACTION:DISPLAY
END:VALARM
END:VEVENT
END:VCALENDAR